;(function(){
    $.ajax({
        type:"get",
        url:"http://127.0.0.1:9090/api/getcoupon",
        dataType:"JSON",
        success:function(data){
            console.log(data);
            $(".coupon").html(template("tpl1",data));
        }
    });
})();